server:
  port: 9094
  
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
      
spring:
  application:
    name: ORDER-SERVICE
#  autoconfigure:
#    exclude: org.springframework.boot.autoconfigure.mongo.embedded.EmbeddedMongoAutoConfiguration
  data:
    mongodb:
      uri: mongodb://localhost:27017/orderdb
      host: localhost
      port: 27017
      database: orderdb
      repositories:
        type: AUTO
